resources:
- ./../../base

patches:
- path: manifests/broadcaster/deployment.yaml
- path: manifests/configMap.yaml

namespace: todo-staging

images:
- name: PROJECT/APP_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-app
  newTag: 3a79e10e4aea3fdcea9e561170c0120ad4b5d515
- name: PROJECT/BACKUP_IMAGE
  newName: gcr.io/dwk-gke-420519/backup-cron
  newTag: 3a79e10e4aea3fdcea9e561170c0120ad4b5d515
- name: PROJECT/BE_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-backend
  newTag: 3a79e10e4aea3fdcea9e561170c0120ad4b5d515
- name: PROJECT/BRDC_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-broadcaster
  newTag: 3a79e10e4aea3fdcea9e561170c0120ad4b5d515
- name: PROJECT/CRON_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-cron
  newTag: 3a79e10e4aea3fdcea9e561170c0120ad4b5d515
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
