resources:
- ./../../base
- ./manifests/bu-cron.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-prod

patches:
  - path: manifests/configMap.yaml

images:
- name: PROJECT/APP_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-app
  newTag: 2dd8d623599ad812bace0c5c90f742e8dc3bff92
- name: PROJECT/BACKUP_IMAGE
  newName: gcr.io/dwk-gke-420519/backup-cron
  newTag: 2dd8d623599ad812bace0c5c90f742e8dc3bff92
- name: PROJECT/BE_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-backend
  newTag: 2dd8d623599ad812bace0c5c90f742e8dc3bff92
- name: PROJECT/BRDC_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-broadcaster
  newTag: 2dd8d623599ad812bace0c5c90f742e8dc3bff92
- name: PROJECT/CRON_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-cron
  newTag: 2dd8d623599ad812bace0c5c90f742e8dc3bff92
