resources:
- ./../../base
- ./manifests/bu-cron.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-prod

images:
- name: PROJECT/APP_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-app:1
- name: PROJECT/BACKUP_IMAGE
  newName: gcr.io/dwk-gke-420519/backup-cron:1
- name: PROJECT/BE_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-backend
  newTag: a905214bffe413a357b38da81eb0fd561da329ec
- name: PROJECT/BRDC_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-broadcaster:1
- name: PROJECT/CRON_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-cron:1