apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:  
      containers:
        - name: todo-broadcaster
          image: PROJECT/BRDC_IMAGE
          env:
          - name: NATS_URL
            valueFrom:
              configMapKeyRef:
                name: todo-generic-conf
                key: NATS_URL
          - name: DISCORD_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: key-secret
                key: discord_hook
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "010m"
              memory: "100Mi"   