apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikipedia-cronjob
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wikipedia-container
            image: PROJECT/CRON_IMAGE
            env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-generic-conf
                  key: BACKEND_URL
          restartPolicy: OnFailure
