apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/APP_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-app:1
- name: PROJECT/BACKUP_IMAGE
  newName: gcr.io/dwk-gke-420519/backup-cron:1
- name: PROJECT/BE_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-backend
  newTag: d95d618afb1d6c014f782f1ec2534b031ed946b5
- name: PROJECT/BRDC_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-broadcaster:1
- name: PROJECT/CRON_IMAGE
  newName: gcr.io/dwk-gke-420519/todo-cron:1





resources:
- manifests/ingress.yaml
- manifests/db_deployment.yaml
- manifests/wikipedia-cron.yaml
- manifests/configMap.yaml
- manifests/backend/deployment.yaml
- manifests/backend/service.yaml
- manifests/broadcaster/deployment.yaml
- manifests/app/deployment.yaml
- manifests/app/service.yaml
- manifests/app/pvc.yaml
