apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-backend-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-load
  template:
    metadata:
      labels:
        app: todo-backend
    spec:  
      containers:
        - name: todo-backend
          image: PROJECT/BE_IMAGE
          env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: todo-generic-conf
                key: DB_URL
          resources:
            limits:
              cpu: "150m"
              memory: "500Mi"
            requests:
              cpu: "015m"
              memory: "100Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 2      